### PR TITLE
117 ensure fresh install works even if ifadv missing

### PR DESCRIPTION
**Pull request by PabRod**
`ifadv` is currently hosted only in [GitHub](https://github.com/elpaco-escience/ifadv). Due to license incompatibility, we cannot just add this dataset to our package. Moreover, CRAN doesn't allow dependencies that live outside of CRAN, so we have no choice but to access it in a less elegant way.

### CODE REVIEW

**Comment by PabRod** [comment]
## Context
Dear @mdingemanse, after wrestling with the `ifadv` problem for a while, I found the following solution:

0. Loading data from a `.csv` is, oddly enough, significantly easier than from R's native format `.rda`. This is particularly true when your data is located on a URL (if you feel curiosity, compare the [rda version](https://github.com/elpaco-escience/talkr/blob/0e48a327cc3754331ca5fedf5899b0fae33e4d53/R/auxs.R) with [the csv one](https://github.com/elpaco-escience/talkr/blob/561cf3c5e326031067377ac291b9e805e57c7dd6/R/auxs.R)
1. So I pushed a `.csv` copy of the dataset to [elpaco-escience/ifadv](https://github.com/elpaco-escience/ifadv), it is redundant, I know, so I kind of hid it in its own branch.

## Request
The tests and vignettes keep running. The snapshots didn't change. But I consider this a potentially critical change in the dataset at its very origin, so it will be great if you can check the results still make sense.

**Review by mdingemanse — APPROVED** [review]
Looks good and tests are stable

**Comment by mdingemanse** [comment]
Yes I quite agree that it would be lovely to redistribute; I remember us spending too much time early 2023 discussing the licensing constraints, and I think the IFADV makers would be scratching their heads about it. I think the current solution works around it in the most CRAN-ready way, which is our proximate goal here so approving

**Comment by mdingemanse** [comment]
I went ahead and merged, let me know if you prefer me to leave this to you as PR author next time

**Pull request merged**
