### PR TITLE
Perform tests in different operative systems

### PR DESCRIPTION
**Pull request by PabRod**

### CODE REVIEW

**Comment by PabRod** [comment]
@mdingemanse, your hypotheses was 100% right. Looking into `png` documentation, I see they even have a section about Differences between OSes. I'll look into this.

**Comment by PabRod** [comment]
The OS dependency of saved plots seems to be a serious issue. See for instance [here](https://www.jumpingrivers.com/blog/r-graphics-cairo-png-pdf-saving/). This is a big problem regarding snapshots.

**Comment by PabRod** [comment]
Next step: take a look at [`ragg`](https://cran.r-project.org/web/packages/ragg/index.html).

**Comment by mdingemanse** [comment]
Just to note that while ragg may offer a solution for this micro issue, we risk getting rabbitholed quite far from the design goals of the package and the aims of the tests. For the functionality of `talkr` it is not important if there happens to be slight pixel level variation in images created in tests. And for tests, the main use case is a single coder iterating over some bit of code and using the tests on their own system (keeping OS constant) as a sanity check that they're not breaking anything.

I can live with the few times where we'd see a very subtle difference that is not a difference because we ran a test on different OSs. The main issue to solve when it comes to different Issues is the stray Rplots.pdf image being created on Windows, not *nix.

**Comment by PabRod** [comment]
Take a look, @mdingemanse. I hot-fixed it by running the snapshot tests conditionally, _i.e.:_, only in Linux.

Surprisingly, there doesn't seem to be a more elegant way of guaranteeing identical outputs across OSs.

**Review by mdingemanse — APPROVED** [review]
okay for now, though I think the more elegant solution will be to break the plot saving code out of the function fully and expect users to find their own OS-specific ways of doing it

**Pull request merged**
