### PR TITLE
change package name to talkR

### LINKED ISSUE #5: Brainstorming names for the R package
@mdingemanse wrote:

I've been brainstorming names. `convoplot()` may be useful as the name of one of the convenience functions we supply but we need something more generic and preferably something that links us to scikit-talk.

I think our best option is **TalkR** (appears not to exist yet). Some others I considered are TalkPlot, TurnVis, DiscourseR, InteractR, but they all seem more overwrought. TalkR is nice and short, uses the common 'r at end' nomenclature, and links to scikit-talk through the common keyword. It can also, of course, be read as 'talker'.

(It would be fun if that also worked as an acronym. A close enough hit is _Tools for Analyzing Language {K, R}_. Perhaps Tools for Analyzing Language in its Key Residence. Or unorthodox spellings like Konversation / Kommunication. If we have kinematic data at some point it could be Tools for Analyzing Language and Kinesics in R :D. But anyway, acronym is nice to have, not a need to have.)

### PR DESCRIPTION
**Pull request by bvreede**
In this PR we match the repository name change to talkR in the DESCRIPTION file.

Closes #5

### CODE REVIEW

**Comment by mdingemanse** [comment]
on review, talkr (all lowercase) is better — see discussion in #5

**Comment by bvreede** [comment]
Excellent! I changed the repo name and updated the DESCRIPTION in this PR :)

**Review by mdingemanse — APPROVED** [review]
good to go!

**Comment by mdingemanse** [comment]
approved — I'll leave it to you @bvreede to merge!

**Comment by bvreede** [comment]
Perfect!! :) Merging!

**Pull request merged**
